### ISSUE TITLE
Type Names can't be found on in the namespace "UnityEngine"

### ISSUE THREAD

**Issue by Moltivie** [KleskBY/Unity3d-Aimbot-Wallhack-ESP#1]
Hello there,
I cannot get `UnityEngine.dll` objects on VS working. I have already had this issue when I wanted to get it working by myself from scratch, but no way. 

A possible temporary but **not verified** fix was that I had to include the entire `*.dll`'s from `GameName_Data\Managed` folder, that allowed me to use objects on VS but hadn't verified the injection and correct execution.

![image](https://user-images.githubusercontent.com/14014692/94343212-ef5c0d80-0016-11eb-9c90-67c8f284bb15.png)

**Comment by DefaultO** [comment]
@Moltivie the message tells you what to do. Add a reference to 'UnityEngine.CoreModule'.

**Comment by Moltivie** [comment]
Thanks!
